minecraft_version=1.21.4

# Fabric loader
loader_version=0.16.10

# Fabric API
fabric_version=0.114.0+1.21.4

# NeoForge
neoforge_version=21.4.156

# Project-specific deps (accessed via mod.prop())
architectury_api_version=15.0.3
fabric_language_kotlin_version=1.13.0+kotlin.2.1.0
kotlin_for_forge_version=5.7.0
mod_menu_version=13.0.3
