modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "vrmmod"
version = "${version}"
displayName = "VRM Mod"
description = "VRM avatar mod for Minecraft"
authors = "Narazaka"

[[dependencies.vrmmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.vrmmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.21.5)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.vrmmod]]
modId = "architectury"
type = "required"
versionRange = "[15.0.0,)"
ordering = "NONE"
side = "CLIENT"
